# Generated by Django 4.2.3 on 2024-02-10 18:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Admin')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='senha',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=6, message='A senha deve ter pelo menos 6 caracteres.')]),
        ),
    ]
