# Generated by Django 4.2.3 on 2024-02-08 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_estacionamento', '0002_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_saida', models.DateTimeField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pago', 'Pago'), ('vencido', 'Vencido')], default='ativo', max_length=20)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento_estacionamento.veiculo')),
            ],
        ),
    ]
