# Generated by Django 4.2.3 on 2024-02-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_estacionamento', '0003_estacionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
