# Generated by Django 4.2.3 on 2024-02-09 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_estacionamento', '0008_alter_cliente_options_alter_estacionamento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
    ]
