# Generated by Django 4.2.3 on 2024-02-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_estacionamento', '0009_remove_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='hora_saida',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido')], default='pendente', max_length=20),
        ),
    ]
